/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import State from './State';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {State};
export const StateSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "anyOf": [
    {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "playerOrder": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "players": {
              "additionalProperties": {
                "defaultProperties": [
                ],
                "properties": {
                  "id": {
                    "type": "string"
                  }
                },
                "required": [
                  "id"
                ],
                "type": "object"
              },
              "defaultProperties": [
              ],
              "type": "object"
            },
            "state": {
              "enum": [
                "UNSTARTED"
              ],
              "type": "string"
            }
          },
          "required": [
            "playerOrder",
            "players",
            "state"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "kind": {
              "enum": [
                "game_state"
              ],
              "type": "string"
            },
            "version": {
              "enum": [
                0
              ],
              "type": "number"
            }
          },
          "required": [
            "kind",
            "version"
          ],
          "type": "object"
        }
      ]
    },
    {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "playerOrder": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "players": {
              "additionalProperties": {
                "defaultProperties": [
                ],
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "submissions": {
                    "items": {
                      "anyOf": [
                        {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "kind": {
                              "enum": [
                                "word"
                              ],
                              "type": "string"
                            },
                            "word": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "kind",
                            "word"
                          ],
                          "type": "object"
                        },
                        {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "drawingId": {
                              "type": "string"
                            },
                            "kind": {
                              "enum": [
                                "drawing"
                              ],
                              "type": "string"
                            }
                          },
                          "required": [
                            "drawingId",
                            "kind"
                          ],
                          "type": "object"
                        }
                      ]
                    },
                    "type": "array"
                  }
                },
                "required": [
                  "id",
                  "submissions"
                ],
                "type": "object"
              },
              "defaultProperties": [
              ],
              "type": "object"
            },
            "state": {
              "enum": [
                "STARTED"
              ],
              "type": "string"
            }
          },
          "required": [
            "playerOrder",
            "players",
            "state"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "kind": {
              "enum": [
                "game_state"
              ],
              "type": "string"
            },
            "version": {
              "enum": [
                0
              ],
              "type": "number"
            }
          },
          "required": [
            "kind",
            "version"
          ],
          "type": "object"
        }
      ]
    },
    {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "displayNames": {
              "$ref": "#/definitions/Record<string,string>"
            },
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "game"
              ],
              "type": "string"
            },
            "playerOrder": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "version": {
              "enum": [
                "v1.1.0"
              ],
              "type": "string"
            }
          },
          "required": [
            "displayNames",
            "gameId",
            "kind",
            "playerOrder",
            "version"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "state": {
              "enum": [
                "UNSTARTED"
              ],
              "type": "string"
            }
          },
          "required": [
            "state"
          ],
          "type": "object"
        }
      ]
    },
    {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "displayNames": {
              "$ref": "#/definitions/Record<string,string>"
            },
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "game"
              ],
              "type": "string"
            },
            "playerOrder": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "version": {
              "enum": [
                "v1.1.0"
              ],
              "type": "string"
            }
          },
          "required": [
            "displayNames",
            "gameId",
            "kind",
            "playerOrder",
            "version"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "state": {
              "enum": [
                "STARTED"
              ],
              "type": "string"
            },
            "submissions": {
              "$ref": "#/definitions/Record<string,Submission[]>"
            }
          },
          "required": [
            "state",
            "submissions"
          ],
          "type": "object"
        }
      ]
    },
    {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "displayNames": {
              "$ref": "#/definitions/Record<string,string>"
            },
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "game"
              ],
              "type": "string"
            },
            "playerOrder": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "version": {
              "enum": [
                "v1.2.0"
              ],
              "type": "string"
            }
          },
          "required": [
            "displayNames",
            "gameId",
            "kind",
            "playerOrder",
            "version"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "state": {
              "enum": [
                "UNSTARTED"
              ],
              "type": "string"
            }
          },
          "required": [
            "state"
          ],
          "type": "object"
        }
      ]
    },
    {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "displayNames": {
              "$ref": "#/definitions/Record<string,string>"
            },
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "game"
              ],
              "type": "string"
            },
            "playerOrder": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "version": {
              "enum": [
                "v1.2.0"
              ],
              "type": "string"
            }
          },
          "required": [
            "displayNames",
            "gameId",
            "kind",
            "playerOrder",
            "version"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "state": {
              "enum": [
                "STARTED"
              ],
              "type": "string"
            },
            "submissions": {
              "$ref": "#/definitions/Record<string,Submission[]>_1"
            }
          },
          "required": [
            "state",
            "submissions"
          ],
          "type": "object"
        }
      ]
    }
  ],
  "definitions": {
    "Record<string,Submission[]>": {
      "defaultProperties": [
      ],
      "description": "Construct a type with a set of properties K of type T",
      "type": "object"
    },
    "Record<string,Submission[]>_1": {
      "defaultProperties": [
      ],
      "description": "Construct a type with a set of properties K of type T",
      "type": "object"
    },
    "Record<string,string>": {
      "defaultProperties": [
      ],
      "description": "Construct a type with a set of properties K of type T",
      "type": "object"
    }
  }
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isState = ajv.compile(StateSchema) as ValidateFunction<State>;
export default function validate(value: unknown): State {
  if (isState(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isState.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'State'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
