/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import Upload from './Upload';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Upload};
export const UploadSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "allOf": [
    {
      "defaultProperties": [
      ],
      "properties": {
        "paths": {
          "items": {
            "items": {
              "type": "number"
            },
            "type": "array"
          },
          "type": "array"
        }
      },
      "required": [
        "paths"
      ],
      "type": "object"
    },
    {
      "defaultProperties": [
      ],
      "properties": {
        "kind": {
          "enum": [
            "drawing"
          ],
          "type": "string"
        }
      },
      "required": [
        "kind"
      ],
      "type": "object"
    }
  ]
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
const rawValidateUpload = ajv.compile(UploadSchema) as ValidateFunction<Upload>;
export default function validate(value: unknown): Upload {
  if (rawValidateUpload(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(rawValidateUpload.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Upload'}) +
      '\n\n' +
      inspect(value),
    );
  }
}