/* tslint:disable */
// generated by typescript-json-validator
import Ajv from 'ajv';
import {ActionRequest, Action, JoinGame, StartGame, MakeMove, Point, Path, Upload, Ref, Submission, Drawing, PlayerGame, UnstartedGame, FirstPromptGame, WaitingForPromptGame, RespondToPromptGame, FinishedGame, Series, SeriesEntry, GameLog, GameLogEntry} from './types';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export const Schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Action": {
      "else": {
        "else": {
          "else": {
            "properties": {
              "kind": {
                "enum": [
                  "join_game",
                  "start_game",
                  "make_move"
                ],
                "type": "string"
              }
            },
            "required": [
              "kind"
            ]
          },
          "if": {
            "properties": {
              "kind": {
                "enum": [
                  "make_move"
                ],
                "type": "string"
              }
            },
            "required": [
              "kind"
            ]
          },
          "then": {
            "defaultProperties": [
            ],
            "properties": {
              "gameId": {
                "type": "string"
              },
              "kind": {
                "enum": [
                  "make_move"
                ],
                "type": "string"
              },
              "playerId": {
                "type": "string"
              },
              "submission": {
                "anyOf": [
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "kind": {
                        "enum": [
                          "word"
                        ],
                        "type": "string"
                      },
                      "word": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "kind",
                      "word"
                    ],
                    "type": "object"
                  },
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "drawing": {
                        "defaultProperties": [
                        ],
                        "properties": {
                          "id": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "id"
                        ],
                        "type": "object"
                      },
                      "kind": {
                        "enum": [
                          "drawing"
                        ],
                        "type": "string"
                      }
                    },
                    "required": [
                      "drawing",
                      "kind"
                    ],
                    "type": "object"
                  }
                ]
              }
            },
            "required": [
              "gameId",
              "kind",
              "playerId",
              "submission"
            ],
            "type": "object"
          }
        },
        "if": {
          "properties": {
            "kind": {
              "enum": [
                "start_game"
              ],
              "type": "string"
            }
          },
          "required": [
            "kind"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "start_game"
              ],
              "type": "string"
            },
            "playerId": {
              "type": "string"
            }
          },
          "required": [
            "gameId",
            "kind",
            "playerId"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "kind": {
            "enum": [
              "join_game"
            ],
            "type": "string"
          }
        },
        "required": [
          "kind"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "gameId": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "join_game"
            ],
            "type": "string"
          },
          "playerId": {
            "type": "string"
          }
        },
        "required": [
          "gameId",
          "kind",
          "playerId"
        ],
        "type": "object"
      }
    },
    "ActionRequest": {
      "defaultProperties": [
      ],
      "properties": {
        "action": {
          "anyOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "join_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "start_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "make_move"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                },
                "submission": {
                  "anyOf": [
                    {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "kind": {
                          "enum": [
                            "word"
                          ],
                          "type": "string"
                        },
                        "word": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "kind",
                        "word"
                      ],
                      "type": "object"
                    },
                    {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "drawing": {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "id": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "id"
                          ],
                          "type": "object"
                        },
                        "kind": {
                          "enum": [
                            "drawing"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "drawing",
                        "kind"
                      ],
                      "type": "object"
                    }
                  ]
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId",
                "submission"
              ],
              "type": "object"
            }
          ]
        },
        "uploads": {
          "additionalProperties": {
            "defaultProperties": [
            ],
            "properties": {
              "drawing": {
                "defaultProperties": [
                ],
                "properties": {
                  "paths": {
                    "items": {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "points": {
                          "items": {
                            "defaultProperties": [
                            ],
                            "properties": {
                              "x": {
                                "type": "number"
                              },
                              "y": {
                                "type": "number"
                              }
                            },
                            "required": [
                              "x",
                              "y"
                            ],
                            "type": "object"
                          },
                          "type": "array"
                        }
                      },
                      "required": [
                        "points"
                      ],
                      "type": "object"
                    },
                    "type": "array"
                  }
                },
                "required": [
                  "paths"
                ],
                "type": "object"
              },
              "kind": {
                "enum": [
                  "drawing"
                ],
                "type": "string"
              }
            },
            "required": [
              "drawing",
              "kind"
            ],
            "type": "object"
          },
          "defaultProperties": [
          ],
          "type": "object"
        }
      },
      "required": [
        "action"
      ],
      "type": "object"
    },
    "Drawing": {
      "defaultProperties": [
      ],
      "properties": {
        "paths": {
          "items": {
            "defaultProperties": [
            ],
            "properties": {
              "points": {
                "items": {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "x": {
                      "type": "number"
                    },
                    "y": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "x",
                    "y"
                  ],
                  "type": "object"
                },
                "type": "array"
              }
            },
            "required": [
              "points"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "paths"
      ],
      "type": "object"
    },
    "FinishedGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "series": {
          "items": {
            "defaultProperties": [
            ],
            "properties": {
              "entries": {
                "items": {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "playerId": {
                      "type": "string"
                    },
                    "submission": {
                      "anyOf": [
                        {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "kind": {
                              "enum": [
                                "word"
                              ],
                              "type": "string"
                            },
                            "word": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "kind",
                            "word"
                          ],
                          "type": "object"
                        },
                        {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "drawing": {
                              "defaultProperties": [
                              ],
                              "properties": {
                                "id": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "id"
                              ],
                              "type": "object"
                            },
                            "kind": {
                              "enum": [
                                "drawing"
                              ],
                              "type": "string"
                            }
                          },
                          "required": [
                            "drawing",
                            "kind"
                          ],
                          "type": "object"
                        }
                      ]
                    }
                  },
                  "required": [
                    "playerId",
                    "submission"
                  ],
                  "type": "object"
                },
                "type": "array"
              }
            },
            "required": [
              "entries"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "GAME_OVER"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "series",
        "state"
      ],
      "type": "object"
    },
    "FirstPromptGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "FIRST_PROMPT"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "state"
      ],
      "type": "object"
    },
    "GameLog": {
      "defaultProperties": [
      ],
      "properties": {
        "entries": {
          "items": {
            "defaultProperties": [
            ],
            "properties": {
              "action": {
                "anyOf": [
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "gameId": {
                        "type": "string"
                      },
                      "kind": {
                        "enum": [
                          "join_game"
                        ],
                        "type": "string"
                      },
                      "playerId": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "gameId",
                      "kind",
                      "playerId"
                    ],
                    "type": "object"
                  },
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "gameId": {
                        "type": "string"
                      },
                      "kind": {
                        "enum": [
                          "start_game"
                        ],
                        "type": "string"
                      },
                      "playerId": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "gameId",
                      "kind",
                      "playerId"
                    ],
                    "type": "object"
                  },
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "gameId": {
                        "type": "string"
                      },
                      "kind": {
                        "enum": [
                          "make_move"
                        ],
                        "type": "string"
                      },
                      "playerId": {
                        "type": "string"
                      },
                      "submission": {
                        "anyOf": [
                          {
                            "defaultProperties": [
                            ],
                            "properties": {
                              "kind": {
                                "enum": [
                                  "word"
                                ],
                                "type": "string"
                              },
                              "word": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "kind",
                              "word"
                            ],
                            "type": "object"
                          },
                          {
                            "defaultProperties": [
                            ],
                            "properties": {
                              "drawing": {
                                "defaultProperties": [
                                ],
                                "properties": {
                                  "id": {
                                    "type": "string"
                                  }
                                },
                                "required": [
                                  "id"
                                ],
                                "type": "object"
                              },
                              "kind": {
                                "enum": [
                                  "drawing"
                                ],
                                "type": "string"
                              }
                            },
                            "required": [
                              "drawing",
                              "kind"
                            ],
                            "type": "object"
                          }
                        ]
                      }
                    },
                    "required": [
                      "gameId",
                      "kind",
                      "playerId",
                      "submission"
                    ],
                    "type": "object"
                  }
                ]
              },
              "timestamp": {
              }
            },
            "required": [
              "action",
              "timestamp"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "lastTimestamp": {
        }
      },
      "required": [
        "entries",
        "lastTimestamp"
      ],
      "type": "object"
    },
    "GameLogEntry": {
      "defaultProperties": [
      ],
      "properties": {
        "action": {
          "anyOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "join_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "start_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "make_move"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                },
                "submission": {
                  "anyOf": [
                    {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "kind": {
                          "enum": [
                            "word"
                          ],
                          "type": "string"
                        },
                        "word": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "kind",
                        "word"
                      ],
                      "type": "object"
                    },
                    {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "drawing": {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "id": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "id"
                          ],
                          "type": "object"
                        },
                        "kind": {
                          "enum": [
                            "drawing"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "drawing",
                        "kind"
                      ],
                      "type": "object"
                    }
                  ]
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId",
                "submission"
              ],
              "type": "object"
            }
          ]
        },
        "timestamp": {
        }
      },
      "required": [
        "action",
        "timestamp"
      ],
      "type": "object"
    },
    "JoinGame": {
      "defaultProperties": [
      ],
      "properties": {
        "gameId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "join_game"
          ],
          "type": "string"
        },
        "playerId": {
          "type": "string"
        }
      },
      "required": [
        "gameId",
        "kind",
        "playerId"
      ],
      "type": "object"
    },
    "MakeMove": {
      "defaultProperties": [
      ],
      "properties": {
        "gameId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "make_move"
          ],
          "type": "string"
        },
        "playerId": {
          "type": "string"
        },
        "submission": {
          "anyOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "kind": {
                  "enum": [
                    "word"
                  ],
                  "type": "string"
                },
                "word": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "word"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "drawing": {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id"
                  ],
                  "type": "object"
                },
                "kind": {
                  "enum": [
                    "drawing"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "drawing",
                "kind"
              ],
              "type": "object"
            }
          ]
        }
      },
      "required": [
        "gameId",
        "kind",
        "playerId",
        "submission"
      ],
      "type": "object"
    },
    "Path": {
      "defaultProperties": [
      ],
      "properties": {
        "points": {
          "items": {
            "defaultProperties": [
            ],
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "points"
      ],
      "type": "object"
    },
    "PlayerGame": {
      "else": {
        "else": {
          "else": {
            "else": {
              "else": {
                "properties": {
                  "state": {
                    "enum": [
                      "UNSTARTED",
                      "FIRST_PROMPT",
                      "WAITING_FOR_PROMPT",
                      "RESPOND_TO_PROMPT",
                      "GAME_OVER"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "state"
                ]
              },
              "if": {
                "properties": {
                  "state": {
                    "enum": [
                      "GAME_OVER"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "state"
                ]
              },
              "then": {
                "defaultProperties": [
                ],
                "properties": {
                  "playerIds": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "series": {
                    "items": {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "entries": {
                          "items": {
                            "defaultProperties": [
                            ],
                            "properties": {
                              "playerId": {
                                "type": "string"
                              },
                              "submission": {
                                "anyOf": [
                                  {
                                    "defaultProperties": [
                                    ],
                                    "properties": {
                                      "kind": {
                                        "enum": [
                                          "word"
                                        ],
                                        "type": "string"
                                      },
                                      "word": {
                                        "type": "string"
                                      }
                                    },
                                    "required": [
                                      "kind",
                                      "word"
                                    ],
                                    "type": "object"
                                  },
                                  {
                                    "defaultProperties": [
                                    ],
                                    "properties": {
                                      "drawing": {
                                        "defaultProperties": [
                                        ],
                                        "properties": {
                                          "id": {
                                            "type": "string"
                                          }
                                        },
                                        "required": [
                                          "id"
                                        ],
                                        "type": "object"
                                      },
                                      "kind": {
                                        "enum": [
                                          "drawing"
                                        ],
                                        "type": "string"
                                      }
                                    },
                                    "required": [
                                      "drawing",
                                      "kind"
                                    ],
                                    "type": "object"
                                  }
                                ]
                              }
                            },
                            "required": [
                              "playerId",
                              "submission"
                            ],
                            "type": "object"
                          },
                          "type": "array"
                        }
                      },
                      "required": [
                        "entries"
                      ],
                      "type": "object"
                    },
                    "type": "array"
                  },
                  "state": {
                    "enum": [
                      "GAME_OVER"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "playerIds",
                  "series",
                  "state"
                ],
                "type": "object"
              }
            },
            "if": {
              "properties": {
                "state": {
                  "enum": [
                    "RESPOND_TO_PROMPT"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "state"
              ]
            },
            "then": {
              "defaultProperties": [
              ],
              "properties": {
                "playerIds": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "prompt": {
                  "anyOf": [
                    {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "kind": {
                          "enum": [
                            "word"
                          ],
                          "type": "string"
                        },
                        "word": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "kind",
                        "word"
                      ],
                      "type": "object"
                    },
                    {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "drawing": {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "id": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "id"
                          ],
                          "type": "object"
                        },
                        "kind": {
                          "enum": [
                            "drawing"
                          ],
                          "type": "string"
                        }
                      },
                      "required": [
                        "drawing",
                        "kind"
                      ],
                      "type": "object"
                    }
                  ]
                },
                "state": {
                  "enum": [
                    "RESPOND_TO_PROMPT"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "playerIds",
                "prompt",
                "state"
              ],
              "type": "object"
            }
          },
          "if": {
            "properties": {
              "state": {
                "enum": [
                  "WAITING_FOR_PROMPT"
                ],
                "type": "string"
              }
            },
            "required": [
              "state"
            ]
          },
          "then": {
            "defaultProperties": [
            ],
            "properties": {
              "playerIds": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "state": {
                "enum": [
                  "WAITING_FOR_PROMPT"
                ],
                "type": "string"
              }
            },
            "required": [
              "playerIds",
              "state"
            ],
            "type": "object"
          }
        },
        "if": {
          "properties": {
            "state": {
              "enum": [
                "FIRST_PROMPT"
              ],
              "type": "string"
            }
          },
          "required": [
            "state"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "playerIds": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "state": {
              "enum": [
                "FIRST_PROMPT"
              ],
              "type": "string"
            }
          },
          "required": [
            "playerIds",
            "state"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "state": {
            "enum": [
              "UNSTARTED"
            ],
            "type": "string"
          }
        },
        "required": [
          "state"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "playerIds": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "state": {
            "enum": [
              "UNSTARTED"
            ],
            "type": "string"
          }
        },
        "required": [
          "playerIds",
          "state"
        ],
        "type": "object"
      }
    },
    "Point": {
      "defaultProperties": [
      ],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "x",
        "y"
      ],
      "type": "object"
    },
    "Ref": {
      "defaultProperties": [
      ],
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "type": "object"
    },
    "RespondToPromptGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "prompt": {
          "anyOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "kind": {
                  "enum": [
                    "word"
                  ],
                  "type": "string"
                },
                "word": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "word"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "drawing": {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id"
                  ],
                  "type": "object"
                },
                "kind": {
                  "enum": [
                    "drawing"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "drawing",
                "kind"
              ],
              "type": "object"
            }
          ]
        },
        "state": {
          "enum": [
            "RESPOND_TO_PROMPT"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "prompt",
        "state"
      ],
      "type": "object"
    },
    "Series": {
      "defaultProperties": [
      ],
      "properties": {
        "entries": {
          "items": {
            "defaultProperties": [
            ],
            "properties": {
              "playerId": {
                "type": "string"
              },
              "submission": {
                "anyOf": [
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "kind": {
                        "enum": [
                          "word"
                        ],
                        "type": "string"
                      },
                      "word": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "kind",
                      "word"
                    ],
                    "type": "object"
                  },
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "drawing": {
                        "defaultProperties": [
                        ],
                        "properties": {
                          "id": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "id"
                        ],
                        "type": "object"
                      },
                      "kind": {
                        "enum": [
                          "drawing"
                        ],
                        "type": "string"
                      }
                    },
                    "required": [
                      "drawing",
                      "kind"
                    ],
                    "type": "object"
                  }
                ]
              }
            },
            "required": [
              "playerId",
              "submission"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "entries"
      ],
      "type": "object"
    },
    "SeriesEntry": {
      "defaultProperties": [
      ],
      "properties": {
        "playerId": {
          "type": "string"
        },
        "submission": {
          "anyOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "kind": {
                  "enum": [
                    "word"
                  ],
                  "type": "string"
                },
                "word": {
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "word"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "drawing": {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id"
                  ],
                  "type": "object"
                },
                "kind": {
                  "enum": [
                    "drawing"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "drawing",
                "kind"
              ],
              "type": "object"
            }
          ]
        }
      },
      "required": [
        "playerId",
        "submission"
      ],
      "type": "object"
    },
    "StartGame": {
      "defaultProperties": [
      ],
      "properties": {
        "gameId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "start_game"
          ],
          "type": "string"
        },
        "playerId": {
          "type": "string"
        }
      },
      "required": [
        "gameId",
        "kind",
        "playerId"
      ],
      "type": "object"
    },
    "Submission": {
      "else": {
        "else": {
          "properties": {
            "kind": {
              "enum": [
                "word",
                "drawing"
              ],
              "type": "string"
            }
          },
          "required": [
            "kind"
          ]
        },
        "if": {
          "properties": {
            "kind": {
              "enum": [
                "drawing"
              ],
              "type": "string"
            }
          },
          "required": [
            "kind"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "drawing": {
              "defaultProperties": [
              ],
              "properties": {
                "id": {
                  "type": "string"
                }
              },
              "required": [
                "id"
              ],
              "type": "object"
            },
            "kind": {
              "enum": [
                "drawing"
              ],
              "type": "string"
            }
          },
          "required": [
            "drawing",
            "kind"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "kind": {
            "enum": [
              "word"
            ],
            "type": "string"
          }
        },
        "required": [
          "kind"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "kind": {
            "enum": [
              "word"
            ],
            "type": "string"
          },
          "word": {
            "type": "string"
          }
        },
        "required": [
          "kind",
          "word"
        ],
        "type": "object"
      }
    },
    "UnstartedGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "UNSTARTED"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "state"
      ],
      "type": "object"
    },
    "Upload": {
      "defaultProperties": [
      ],
      "properties": {
        "drawing": {
          "defaultProperties": [
          ],
          "properties": {
            "paths": {
              "items": {
                "defaultProperties": [
                ],
                "properties": {
                  "points": {
                    "items": {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "x": {
                          "type": "number"
                        },
                        "y": {
                          "type": "number"
                        }
                      },
                      "required": [
                        "x",
                        "y"
                      ],
                      "type": "object"
                    },
                    "type": "array"
                  }
                },
                "required": [
                  "points"
                ],
                "type": "object"
              },
              "type": "array"
            }
          },
          "required": [
            "paths"
          ],
          "type": "object"
        },
        "kind": {
          "enum": [
            "drawing"
          ],
          "type": "string"
        }
      },
      "required": [
        "drawing",
        "kind"
      ],
      "type": "object"
    },
    "WaitingForPromptGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "WAITING_FOR_PROMPT"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "state"
      ],
      "type": "object"
    }
  }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'ActionRequest'): (value: unknown) => ActionRequest;
export function validate(typeName: 'Action'): (value: unknown) => Action;
export function validate(typeName: 'JoinGame'): (value: unknown) => JoinGame;
export function validate(typeName: 'StartGame'): (value: unknown) => StartGame;
export function validate(typeName: 'MakeMove'): (value: unknown) => MakeMove;
export function validate(typeName: 'Point'): (value: unknown) => Point;
export function validate(typeName: 'Path'): (value: unknown) => Path;
export function validate(typeName: 'Upload'): (value: unknown) => Upload;
export function validate(typeName: 'Ref'): (value: unknown) => Ref;
export function validate(typeName: 'Submission'): (value: unknown) => Submission;
export function validate(typeName: 'Drawing'): (value: unknown) => Drawing;
export function validate(typeName: 'PlayerGame'): (value: unknown) => PlayerGame;
export function validate(typeName: 'UnstartedGame'): (value: unknown) => UnstartedGame;
export function validate(typeName: 'FirstPromptGame'): (value: unknown) => FirstPromptGame;
export function validate(typeName: 'WaitingForPromptGame'): (value: unknown) => WaitingForPromptGame;
export function validate(typeName: 'RespondToPromptGame'): (value: unknown) => RespondToPromptGame;
export function validate(typeName: 'FinishedGame'): (value: unknown) => FinishedGame;
export function validate(typeName: 'Series'): (value: unknown) => Series;
export function validate(typeName: 'SeriesEntry'): (value: unknown) => SeriesEntry;
export function validate(typeName: 'GameLog'): (value: unknown) => GameLog;
export function validate(typeName: 'GameLogEntry'): (value: unknown) => GameLogEntry;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
    }
  
    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: typeName}),
      );
    }

    return value as any;
  };
}