/* tslint:disable */
// generated by typescript-json-validator
import Ajv = require('ajv');
import { UnstartedGame, UnstartedGamePlayer, StartedGame, StartedGamePlayer, Submission, Game } from './1.1.1';
export const ajv = new Ajv({ "allErrors": true, "coerceTypes": false, "format": "fast", "nullable": true, "unicode": true, "uniqueItems": true, "useDefaults": true });

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export const Schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Game": {
            "else": {
                "else": {
                    "properties": {
                        "state": {
                            "enum": [
                                "UNSTARTED",
                                "STARTED"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "state"
                    ]
                },
                "if": {
                    "properties": {
                        "state": {
                            "enum": [
                                "STARTED"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "state"
                    ]
                },
                "then": {
                    "$ref": "#/definitions/StartedGame"
                }
            },
            "if": {
                "properties": {
                    "state": {
                        "enum": [
                            "UNSTARTED"
                        ],
                        "type": "string"
                    }
                },
                "required": [
                    "state"
                ]
            },
            "then": {
                "$ref": "#/definitions/UnstartedGame"
            }
        },
        "StartedGame": {
            "defaultProperties": [
            ],
            "properties": {
                "players": {
                    "items": {
                        "$ref": "#/definitions/StartedGamePlayer"
                    },
                    "type": "array"
                },
                "state": {
                    "enum": [
                        "STARTED"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "players",
                "state"
            ],
            "type": "object"
        },
        "StartedGamePlayer": {
            "defaultProperties": [
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "submissions": {
                    "items": {
                        "anyOf": [
                            {
                                "defaultProperties": [
                                ],
                                "properties": {
                                    "kind": {
                                        "enum": [
                                            "word"
                                        ],
                                        "type": "string"
                                    },
                                    "word": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "kind",
                                    "word"
                                ],
                                "type": "object"
                            },
                            {
                                "defaultProperties": [
                                ],
                                "properties": {
                                    "drawingId": {
                                        "type": "string"
                                    },
                                    "kind": {
                                        "enum": [
                                            "drawing"
                                        ],
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "drawingId",
                                    "kind"
                                ],
                                "type": "object"
                            }
                        ]
                    },
                    "type": "array"
                }
            },
            "required": [
                "displayName",
                "id",
                "submissions"
            ],
            "type": "object"
        },
        "Submission": {
            "else": {
                "else": {
                    "properties": {
                        "kind": {
                            "enum": [
                                "word",
                                "drawing"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "kind"
                    ]
                },
                "if": {
                    "properties": {
                        "kind": {
                            "enum": [
                                "drawing"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "kind"
                    ]
                },
                "then": {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "drawingId": {
                            "type": "string"
                        },
                        "kind": {
                            "enum": [
                                "drawing"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "drawingId",
                        "kind"
                    ],
                    "type": "object"
                }
            },
            "if": {
                "properties": {
                    "kind": {
                        "enum": [
                            "word"
                        ],
                        "type": "string"
                    }
                },
                "required": [
                    "kind"
                ]
            },
            "then": {
                "defaultProperties": [
                ],
                "properties": {
                    "kind": {
                        "enum": [
                            "word"
                        ],
                        "type": "string"
                    },
                    "word": {
                        "type": "string"
                    }
                },
                "required": [
                    "kind",
                    "word"
                ],
                "type": "object"
            }
        },
        "UnstartedGame": {
            "defaultProperties": [
            ],
            "properties": {
                "players": {
                    "items": {
                        "$ref": "#/definitions/UnstartedGamePlayer"
                    },
                    "type": "array"
                },
                "state": {
                    "enum": [
                        "UNSTARTED"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "players",
                "state"
            ],
            "type": "object"
        },
        "UnstartedGamePlayer": {
            "defaultProperties": [
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            },
            "required": [
                "displayName",
                "id"
            ],
            "type": "object"
        }
    }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'UnstartedGame'): (value: unknown) => UnstartedGame;
export function validate(typeName: 'UnstartedGamePlayer'): (value: unknown) => UnstartedGamePlayer;
export function validate(typeName: 'StartedGame'): (value: unknown) => StartedGame;
export function validate(typeName: 'StartedGamePlayer'): (value: unknown) => StartedGamePlayer;
export function validate(typeName: 'Submission'): (value: unknown) => Submission;
export function validate(typeName: 'Game'): (value: unknown) => Game;
export function validate(typeName: string): (value: unknown) => any {
    const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
    return (value: unknown): any => {
        if (!validator) {
            throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
        }

        const valid = validator(value);

        if (!valid) {
            throw new Error(
                'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), { dataVar: typeName }),
            );
        }

        return value as any;
    };
}
