/* tslint:disable */
// generated by typescript-json-validator
import Ajv = require('ajv');
import { CreateGameAction, JoinGameAction, StartGameAction, MakeMoveAction, Submission, Action, Error, BoringPlayerGame, RespondToPromptPlayerGame, FinishedPlayerGame, ExportedSeries, ExportedSeriesEntry, ExportedPlayer, PlayerGame } from './1.2';
export const ajv = new Ajv({ "allErrors": true, "coerceTypes": false, "format": "fast", "nullable": true, "unicode": true, "uniqueItems": true, "useDefaults": true });

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export const Schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Action": {
            "else": {
                "else": {
                    "else": {
                        "else": {
                            "properties": {
                                "kind": {
                                    "enum": [
                                        "create_game",
                                        "join_game",
                                        "start_game",
                                        "make_move"
                                    ],
                                    "type": "string"
                                }
                            },
                            "required": [
                                "kind"
                            ]
                        },
                        "if": {
                            "properties": {
                                "kind": {
                                    "enum": [
                                        "make_move"
                                    ],
                                    "type": "string"
                                }
                            },
                            "required": [
                                "kind"
                            ]
                        },
                        "then": {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "gameId": {
                                    "maxLength": 1024,
                                    "minLength": 1,
                                    "pattern": "^[a-zA-Z0-9_-]*$",
                                    "type": "string"
                                },
                                "kind": {
                                    "enum": [
                                        "make_move"
                                    ],
                                    "type": "string"
                                },
                                "playerId": {
                                    "maxLength": 1024,
                                    "minLength": 1,
                                    "pattern": "^[a-zA-Z0-9_-]*$",
                                    "type": "string"
                                },
                                "submission": {
                                    "anyOf": [
                                        {
                                            "defaultProperties": [
                                            ],
                                            "properties": {
                                                "kind": {
                                                    "enum": [
                                                        "word"
                                                    ],
                                                    "type": "string"
                                                },
                                                "word": {
                                                    "maxLength": 1024,
                                                    "minLength": 1,
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "kind",
                                                "word"
                                            ],
                                            "type": "object"
                                        },
                                        {
                                            "defaultProperties": [
                                            ],
                                            "properties": {
                                                "drawingId": {
                                                    "type": "string"
                                                },
                                                "kind": {
                                                    "enum": [
                                                        "drawing"
                                                    ],
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "drawingId",
                                                "kind"
                                            ],
                                            "type": "object"
                                        }
                                    ]
                                },
                                "version": {
                                    "enum": [
                                        "1.2"
                                    ],
                                    "type": "string"
                                }
                            },
                            "required": [
                                "gameId",
                                "kind",
                                "playerId",
                                "submission",
                                "version"
                            ],
                            "type": "object"
                        }
                    },
                    "if": {
                        "properties": {
                            "kind": {
                                "enum": [
                                    "start_game"
                                ],
                                "type": "string"
                            }
                        },
                        "required": [
                            "kind"
                        ]
                    },
                    "then": {
                        "$ref": "#/definitions/StartGameAction"
                    }
                },
                "if": {
                    "properties": {
                        "kind": {
                            "enum": [
                                "join_game"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "kind"
                    ]
                },
                "then": {
                    "$ref": "#/definitions/JoinGameAction"
                }
            },
            "if": {
                "properties": {
                    "kind": {
                        "enum": [
                            "create_game"
                        ],
                        "type": "string"
                    }
                },
                "required": [
                    "kind"
                ]
            },
            "then": {
                "$ref": "#/definitions/CreateGameAction"
            }
        },
        "BoringPlayerGame": {
            "defaultProperties": [
            ],
            "properties": {
                "players": {
                    "items": {
                        "$ref": "#/definitions/ExportedPlayer"
                    },
                    "type": "array"
                },
                "state": {
                    "enum": [
                        "FIRST_PROMPT",
                        "UNSTARTED",
                        "WAITING_FOR_PROMPT"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "players",
                "state"
            ],
            "type": "object"
        },
        "CreateGameAction": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "create_game"
                    ],
                    "type": "string"
                },
                "shortCode": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.2"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "shortCode",
                "version"
            ],
            "type": "object"
        },
        "Error": {
            "anyOf": [
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "gameId": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "GAME_NOT_STARTED"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                400
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.0"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "gameId",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "gameId": {
                            "type": "string"
                        },
                        "playerId": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "PLAYER_NOT_IN_GAME"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                403
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.0"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "gameId",
                        "playerId",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "gameId": {
                            "type": "string"
                        },
                        "playerId": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "MOVE_PLAYED_OUT_OF_TURN"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                400
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.0"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "gameId",
                        "playerId",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "gameId": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "GAME_IS_OVER"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                400
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.0"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "gameId",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "got": {
                            "enum": [
                                "drawing",
                                "word"
                            ],
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "INCORRECT_SUBMISSION_KIND"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                400
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.0"
                            ],
                            "type": "string"
                        },
                        "wanted": {
                            "enum": [
                                "drawing",
                                "word"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "got",
                        "status",
                        "status_code",
                        "version",
                        "wanted"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "gameId": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "GAME_ALREADY_STARTED"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                400
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.0"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "gameId",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "gameId": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "GAME_NOT_FOUND"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                404
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.2"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "gameId",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "gameId": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "GAME_ALREADY_EXISTS"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                400
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.2"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "gameId",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "shortCode": {
                            "type": "string"
                        },
                        "status": {
                            "enum": [
                                "SHORT_CODE_IN_USE"
                            ],
                            "type": "string"
                        },
                        "status_code": {
                            "enum": [
                                400
                            ],
                            "type": "number"
                        },
                        "version": {
                            "enum": [
                                "1.2"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "shortCode",
                        "status",
                        "status_code",
                        "version"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "status": {
                            "type": "string"
                        },
                        "status_code": {
                            "type": "number"
                        },
                        "true_version": {
                            "type": "string"
                        },
                        "version": {
                            "enum": [
                                "UNKNOWN"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "status",
                        "status_code",
                        "true_version",
                        "version"
                    ],
                    "type": "object"
                }
            ]
        },
        "ExportedPlayer": {
            "defaultProperties": [
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            },
            "required": [
                "displayName",
                "id"
            ],
            "type": "object"
        },
        "ExportedSeries": {
            "defaultProperties": [
            ],
            "properties": {
                "entries": {
                    "items": {
                        "defaultProperties": [
                        ],
                        "properties": {
                            "playerId": {
                                "type": "string"
                            },
                            "submission": {
                                "anyOf": [
                                    {
                                        "defaultProperties": [
                                        ],
                                        "properties": {
                                            "kind": {
                                                "enum": [
                                                    "word"
                                                ],
                                                "type": "string"
                                            },
                                            "word": {
                                                "maxLength": 1024,
                                                "minLength": 1,
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "kind",
                                            "word"
                                        ],
                                        "type": "object"
                                    },
                                    {
                                        "defaultProperties": [
                                        ],
                                        "properties": {
                                            "drawingId": {
                                                "type": "string"
                                            },
                                            "kind": {
                                                "enum": [
                                                    "drawing"
                                                ],
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "drawingId",
                                            "kind"
                                        ],
                                        "type": "object"
                                    }
                                ]
                            }
                        },
                        "required": [
                            "playerId",
                            "submission"
                        ],
                        "type": "object"
                    },
                    "type": "array"
                }
            },
            "required": [
                "entries"
            ],
            "type": "object"
        },
        "ExportedSeriesEntry": {
            "defaultProperties": [
            ],
            "properties": {
                "playerId": {
                    "type": "string"
                },
                "submission": {
                    "anyOf": [
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "kind": {
                                    "enum": [
                                        "word"
                                    ],
                                    "type": "string"
                                },
                                "word": {
                                    "maxLength": 1024,
                                    "minLength": 1,
                                    "type": "string"
                                }
                            },
                            "required": [
                                "kind",
                                "word"
                            ],
                            "type": "object"
                        },
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "drawingId": {
                                    "type": "string"
                                },
                                "kind": {
                                    "enum": [
                                        "drawing"
                                    ],
                                    "type": "string"
                                }
                            },
                            "required": [
                                "drawingId",
                                "kind"
                            ],
                            "type": "object"
                        }
                    ]
                }
            },
            "required": [
                "playerId",
                "submission"
            ],
            "type": "object"
        },
        "FinishedPlayerGame": {
            "defaultProperties": [
            ],
            "properties": {
                "players": {
                    "items": {
                        "$ref": "#/definitions/ExportedPlayer"
                    },
                    "type": "array"
                },
                "series": {
                    "items": {
                        "defaultProperties": [
                        ],
                        "properties": {
                            "entries": {
                                "items": {
                                    "defaultProperties": [
                                    ],
                                    "properties": {
                                        "playerId": {
                                            "type": "string"
                                        },
                                        "submission": {
                                            "anyOf": [
                                                {
                                                    "defaultProperties": [
                                                    ],
                                                    "properties": {
                                                        "kind": {
                                                            "enum": [
                                                                "word"
                                                            ],
                                                            "type": "string"
                                                        },
                                                        "word": {
                                                            "maxLength": 1024,
                                                            "minLength": 1,
                                                            "type": "string"
                                                        }
                                                    },
                                                    "required": [
                                                        "kind",
                                                        "word"
                                                    ],
                                                    "type": "object"
                                                },
                                                {
                                                    "defaultProperties": [
                                                    ],
                                                    "properties": {
                                                        "drawingId": {
                                                            "type": "string"
                                                        },
                                                        "kind": {
                                                            "enum": [
                                                                "drawing"
                                                            ],
                                                            "type": "string"
                                                        }
                                                    },
                                                    "required": [
                                                        "drawingId",
                                                        "kind"
                                                    ],
                                                    "type": "object"
                                                }
                                            ]
                                        }
                                    },
                                    "required": [
                                        "playerId",
                                        "submission"
                                    ],
                                    "type": "object"
                                },
                                "type": "array"
                            }
                        },
                        "required": [
                            "entries"
                        ],
                        "type": "object"
                    },
                    "type": "array"
                },
                "state": {
                    "enum": [
                        "GAME_OVER"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "players",
                "series",
                "state"
            ],
            "type": "object"
        },
        "JoinGameAction": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "join_game"
                    ],
                    "type": "string"
                },
                "playerDisplayName": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "type": "string"
                },
                "playerId": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.2"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "playerDisplayName",
                "playerId",
                "version"
            ],
            "type": "object"
        },
        "MakeMoveAction": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "make_move"
                    ],
                    "type": "string"
                },
                "playerId": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "submission": {
                    "anyOf": [
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "kind": {
                                    "enum": [
                                        "word"
                                    ],
                                    "type": "string"
                                },
                                "word": {
                                    "maxLength": 1024,
                                    "minLength": 1,
                                    "type": "string"
                                }
                            },
                            "required": [
                                "kind",
                                "word"
                            ],
                            "type": "object"
                        },
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "drawingId": {
                                    "type": "string"
                                },
                                "kind": {
                                    "enum": [
                                        "drawing"
                                    ],
                                    "type": "string"
                                }
                            },
                            "required": [
                                "drawingId",
                                "kind"
                            ],
                            "type": "object"
                        }
                    ]
                },
                "version": {
                    "enum": [
                        "1.2"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "playerId",
                "submission",
                "version"
            ],
            "type": "object"
        },
        "PlayerGame": {
            "anyOf": [
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "players": {
                            "items": {
                                "$ref": "#/definitions/ExportedPlayer"
                            },
                            "type": "array"
                        },
                        "state": {
                            "enum": [
                                "FIRST_PROMPT",
                                "UNSTARTED",
                                "WAITING_FOR_PROMPT"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "players",
                        "state"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "players": {
                            "items": {
                                "$ref": "#/definitions/ExportedPlayer"
                            },
                            "type": "array"
                        },
                        "prompt": {
                            "anyOf": [
                                {
                                    "defaultProperties": [
                                    ],
                                    "properties": {
                                        "kind": {
                                            "enum": [
                                                "word"
                                            ],
                                            "type": "string"
                                        },
                                        "word": {
                                            "maxLength": 1024,
                                            "minLength": 1,
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "kind",
                                        "word"
                                    ],
                                    "type": "object"
                                },
                                {
                                    "defaultProperties": [
                                    ],
                                    "properties": {
                                        "drawingId": {
                                            "type": "string"
                                        },
                                        "kind": {
                                            "enum": [
                                                "drawing"
                                            ],
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "drawingId",
                                        "kind"
                                    ],
                                    "type": "object"
                                }
                            ]
                        },
                        "state": {
                            "enum": [
                                "RESPOND_TO_PROMPT"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "players",
                        "prompt",
                        "state"
                    ],
                    "type": "object"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "players": {
                            "items": {
                                "$ref": "#/definitions/ExportedPlayer"
                            },
                            "type": "array"
                        },
                        "series": {
                            "items": {
                                "defaultProperties": [
                                ],
                                "properties": {
                                    "entries": {
                                        "items": {
                                            "defaultProperties": [
                                            ],
                                            "properties": {
                                                "playerId": {
                                                    "type": "string"
                                                },
                                                "submission": {
                                                    "anyOf": [
                                                        {
                                                            "defaultProperties": [
                                                            ],
                                                            "properties": {
                                                                "kind": {
                                                                    "enum": [
                                                                        "word"
                                                                    ],
                                                                    "type": "string"
                                                                },
                                                                "word": {
                                                                    "maxLength": 1024,
                                                                    "minLength": 1,
                                                                    "type": "string"
                                                                }
                                                            },
                                                            "required": [
                                                                "kind",
                                                                "word"
                                                            ],
                                                            "type": "object"
                                                        },
                                                        {
                                                            "defaultProperties": [
                                                            ],
                                                            "properties": {
                                                                "drawingId": {
                                                                    "type": "string"
                                                                },
                                                                "kind": {
                                                                    "enum": [
                                                                        "drawing"
                                                                    ],
                                                                    "type": "string"
                                                                }
                                                            },
                                                            "required": [
                                                                "drawingId",
                                                                "kind"
                                                            ],
                                                            "type": "object"
                                                        }
                                                    ]
                                                }
                                            },
                                            "required": [
                                                "playerId",
                                                "submission"
                                            ],
                                            "type": "object"
                                        },
                                        "type": "array"
                                    }
                                },
                                "required": [
                                    "entries"
                                ],
                                "type": "object"
                            },
                            "type": "array"
                        },
                        "state": {
                            "enum": [
                                "GAME_OVER"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "players",
                        "series",
                        "state"
                    ],
                    "type": "object"
                }
            ]
        },
        "RespondToPromptPlayerGame": {
            "defaultProperties": [
            ],
            "properties": {
                "players": {
                    "items": {
                        "$ref": "#/definitions/ExportedPlayer"
                    },
                    "type": "array"
                },
                "prompt": {
                    "anyOf": [
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "kind": {
                                    "enum": [
                                        "word"
                                    ],
                                    "type": "string"
                                },
                                "word": {
                                    "maxLength": 1024,
                                    "minLength": 1,
                                    "type": "string"
                                }
                            },
                            "required": [
                                "kind",
                                "word"
                            ],
                            "type": "object"
                        },
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "drawingId": {
                                    "type": "string"
                                },
                                "kind": {
                                    "enum": [
                                        "drawing"
                                    ],
                                    "type": "string"
                                }
                            },
                            "required": [
                                "drawingId",
                                "kind"
                            ],
                            "type": "object"
                        }
                    ]
                },
                "state": {
                    "enum": [
                        "RESPOND_TO_PROMPT"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "players",
                "prompt",
                "state"
            ],
            "type": "object"
        },
        "StartGameAction": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "start_game"
                    ],
                    "type": "string"
                },
                "playerId": {
                    "maxLength": 1024,
                    "minLength": 1,
                    "pattern": "^[a-zA-Z0-9_-]*$",
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.2"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "playerId",
                "version"
            ],
            "type": "object"
        },
        "Submission": {
            "else": {
                "else": {
                    "properties": {
                        "kind": {
                            "enum": [
                                "word",
                                "drawing"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "kind"
                    ]
                },
                "if": {
                    "properties": {
                        "kind": {
                            "enum": [
                                "drawing"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "kind"
                    ]
                },
                "then": {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "drawingId": {
                            "type": "string"
                        },
                        "kind": {
                            "enum": [
                                "drawing"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "drawingId",
                        "kind"
                    ],
                    "type": "object"
                }
            },
            "if": {
                "properties": {
                    "kind": {
                        "enum": [
                            "word"
                        ],
                        "type": "string"
                    }
                },
                "required": [
                    "kind"
                ]
            },
            "then": {
                "defaultProperties": [
                ],
                "properties": {
                    "kind": {
                        "enum": [
                            "word"
                        ],
                        "type": "string"
                    },
                    "word": {
                        "maxLength": 1024,
                        "minLength": 1,
                        "type": "string"
                    }
                },
                "required": [
                    "kind",
                    "word"
                ],
                "type": "object"
            }
        }
    }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'CreateGameAction'): (value: unknown) => CreateGameAction;
export function validate(typeName: 'JoinGameAction'): (value: unknown) => JoinGameAction;
export function validate(typeName: 'StartGameAction'): (value: unknown) => StartGameAction;
export function validate(typeName: 'MakeMoveAction'): (value: unknown) => MakeMoveAction;
export function validate(typeName: 'Submission'): (value: unknown) => Submission;
export function validate(typeName: 'Action'): (value: unknown) => Action;
export function validate(typeName: 'Error'): (value: unknown) => Error;
export function validate(typeName: 'BoringPlayerGame'): (value: unknown) => BoringPlayerGame;
export function validate(typeName: 'RespondToPromptPlayerGame'): (value: unknown) => RespondToPromptPlayerGame;
export function validate(typeName: 'FinishedPlayerGame'): (value: unknown) => FinishedPlayerGame;
export function validate(typeName: 'ExportedSeries'): (value: unknown) => ExportedSeries;
export function validate(typeName: 'ExportedSeriesEntry'): (value: unknown) => ExportedSeriesEntry;
export function validate(typeName: 'ExportedPlayer'): (value: unknown) => ExportedPlayer;
export function validate(typeName: 'PlayerGame'): (value: unknown) => PlayerGame;
export function validate(typeName: string): (value: unknown) => any {
    const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
    return (value: unknown): any => {
        if (!validator) {
            throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
        }

        const valid = validator(value);

        if (!valid) {
            throw new Error(
                'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), { dataVar: typeName }),
            );
        }

        return value as any;
    };
}
