/* tslint:disable */
// generated by typescript-json-validator
import Ajv = require('ajv');
import {AnyIndex, AnyAction, AnyState, AnyExport} from './index';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {AnyIndex, AnyAction, AnyState, AnyExport};
export const Schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AnyAction": {
      "else": {
        "else": {
          "properties": {
            "version": {
              "enum": [
                "v1.0",
                "v1.1"
              ],
              "type": "string"
            }
          },
          "required": [
            "version"
          ]
        },
        "if": {
          "properties": {
            "version": {
              "enum": [
                "v1.1"
              ],
              "type": "string"
            }
          },
          "required": [
            "version"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "join_game"
              ],
              "type": "string"
            },
            "playerId": {
              "type": "string"
            },
            "version": {
              "enum": [
                "v1.1"
              ],
              "type": "string"
            }
          },
          "required": [
            "gameId",
            "kind",
            "playerId",
            "version"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "version": {
            "enum": [
              "v1.0"
            ],
            "type": "string"
          }
        },
        "required": [
          "version"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "gameId": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "join_game"
            ],
            "type": "string"
          },
          "playerId": {
            "type": "string"
          },
          "version": {
            "enum": [
              "v1.0"
            ],
            "type": "string"
          }
        },
        "required": [
          "gameId",
          "kind",
          "playerId",
          "version"
        ],
        "type": "object"
      }
    },
    "AnyExport": {
      "else": {
        "else": {
          "properties": {
            "version": {
              "enum": [
                "v1.0",
                "v1.1"
              ],
              "type": "string"
            }
          },
          "required": [
            "version"
          ]
        },
        "if": {
          "properties": {
            "version": {
              "enum": [
                "v1.1"
              ],
              "type": "string"
            }
          },
          "required": [
            "version"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "player_game"
              ],
              "type": "string"
            },
            "playerId": {
              "type": "string"
            },
            "players": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "version": {
              "enum": [
                "v1.1"
              ],
              "type": "string"
            }
          },
          "required": [
            "gameId",
            "kind",
            "playerId",
            "players",
            "version"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "version": {
            "enum": [
              "v1.0"
            ],
            "type": "string"
          }
        },
        "required": [
          "version"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "gameId": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "player_game"
            ],
            "type": "string"
          },
          "playerId": {
            "type": "string"
          },
          "players": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "version": {
            "enum": [
              "v1.0"
            ],
            "type": "string"
          }
        },
        "required": [
          "gameId",
          "kind",
          "playerId",
          "players",
          "version"
        ],
        "type": "object"
      }
    },
    "AnyIndex": {
      "anyOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "Action": {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "join_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                },
                "version": {
                  "enum": [
                    "v1.0"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId",
                "version"
              ],
              "type": "object"
            },
            "Export": {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "player_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                },
                "players": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "version": {
                  "enum": [
                    "v1.0"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId",
                "players",
                "version"
              ],
              "type": "object"
            },
            "State": {
              "defaultProperties": [
              ],
              "properties": {
                "kind": {
                  "enum": [
                    "root"
                  ],
                  "type": "string"
                },
                "players": {
                  "$ref": "#/definitions/Record<string,string[]>"
                },
                "version": {
                  "enum": [
                    "v1.0"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "players",
                "version"
              ],
              "type": "object"
            }
          },
          "required": [
            "Action",
            "Export",
            "State"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "Action": {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "join_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                },
                "version": {
                  "enum": [
                    "v1.1"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId",
                "version"
              ],
              "type": "object"
            },
            "Export": {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "player_game"
                  ],
                  "type": "string"
                },
                "playerId": {
                  "type": "string"
                },
                "players": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "version": {
                  "enum": [
                    "v1.1"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "playerId",
                "players",
                "version"
              ],
              "type": "object"
            },
            "State": {
              "defaultProperties": [
              ],
              "properties": {
                "gameId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "game"
                  ],
                  "type": "string"
                },
                "players": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                },
                "version": {
                  "enum": [
                    "v1.1"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "gameId",
                "kind",
                "players",
                "version"
              ],
              "type": "object"
            }
          },
          "required": [
            "Action",
            "Export",
            "State"
          ],
          "type": "object"
        }
      ]
    },
    "AnyState": {
      "anyOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "kind": {
              "enum": [
                "root"
              ],
              "type": "string"
            },
            "players": {
              "$ref": "#/definitions/Record<string,string[]>"
            },
            "version": {
              "enum": [
                "v1.0"
              ],
              "type": "string"
            }
          },
          "required": [
            "kind",
            "players",
            "version"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "game"
              ],
              "type": "string"
            },
            "players": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "version": {
              "enum": [
                "v1.1"
              ],
              "type": "string"
            }
          },
          "required": [
            "gameId",
            "kind",
            "players",
            "version"
          ],
          "type": "object"
        }
      ]
    },
    "Record<string,string[]>": {
      "defaultProperties": [
      ],
      "description": "Construct a type with a set of properties K of type T",
      "type": "object"
    }
  }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'AnyIndex'): (value: unknown) => AnyIndex;
export function validate(typeName: 'AnyAction'): (value: unknown) => AnyAction;
export function validate(typeName: 'AnyState'): (value: unknown) => AnyState;
export function validate(typeName: 'AnyExport'): (value: unknown) => AnyExport;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
    }
  
    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: typeName}),
      );
    }

    return value as any;
  };
}