/* tslint:disable */
// generated by typescript-json-validator
import Ajv = require('ajv');
import { Timestamp, Timestamped, NumberValue, Symlink, JoinGameAction1_0, Action1_0, Game1_0, TaggedGame1_0, SavedAction, SavedState, CreateGameAction1_1, JoinGameAction1_1, Action1_1, UncreatedGame1_1, CreatedGame1_1, Game1_1, TaggedGame1_1, AnyAction, TimestampedAction } from './index';
export const ajv = new Ajv({ "allErrors": true, "coerceTypes": false, "format": "fast", "nullable": true, "unicode": true, "uniqueItems": true, "useDefaults": true });

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export { Timestamp, Timestamped, NumberValue, Symlink, JoinGameAction1_0, Action1_0, Game1_0, TaggedGame1_0, SavedAction, SavedState, CreateGameAction1_1, JoinGameAction1_1, Action1_1, UncreatedGame1_1, CreatedGame1_1, Game1_1, TaggedGame1_1, AnyAction, TimestampedAction };
export const Schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Action1_0": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "join_game"
                    ],
                    "type": "string"
                },
                "playerId": {
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.0"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "playerId",
                "version"
            ],
            "type": "object"
        },
        "Action1_1": {
            "else": {
                "else": {
                    "properties": {
                        "kind": {
                            "enum": [
                                "create_game",
                                "join_game"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "kind"
                    ]
                },
                "if": {
                    "properties": {
                        "kind": {
                            "enum": [
                                "join_game"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "kind"
                    ]
                },
                "then": {
                    "$ref": "#/definitions/JoinGameAction1_1"
                }
            },
            "if": {
                "properties": {
                    "kind": {
                        "enum": [
                            "create_game"
                        ],
                        "type": "string"
                    }
                },
                "required": [
                    "kind"
                ]
            },
            "then": {
                "$ref": "#/definitions/CreateGameAction1_1"
            }
        },
        "AnyAction": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "join_game"
                    ],
                    "type": "string"
                },
                "playerId": {
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.0"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "playerId",
                "version"
            ],
            "type": "object"
        },
        "CreateGameAction1_1": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "create_game"
                    ],
                    "type": "string"
                },
                "shortCode": {
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.1"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "shortCode",
                "version"
            ],
            "type": "object"
        },
        "CreatedGame1_1": {
            "defaultProperties": [
            ],
            "properties": {
                "players": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "shortCode": {
                    "type": "string"
                },
                "state": {
                    "enum": [
                        "CREATED"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "players",
                "shortCode",
                "state"
            ],
            "type": "object"
        },
        "Game1_0": {
            "defaultProperties": [
            ],
            "properties": {
                "players": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "required": [
                "players"
            ],
            "type": "object"
        },
        "Game1_1": {
            "else": {
                "else": {
                    "properties": {
                        "state": {
                            "enum": [
                                "UNCREATED",
                                "CREATED"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "state"
                    ]
                },
                "if": {
                    "properties": {
                        "state": {
                            "enum": [
                                "CREATED"
                            ],
                            "type": "string"
                        }
                    },
                    "required": [
                        "state"
                    ]
                },
                "then": {
                    "$ref": "#/definitions/CreatedGame1_1"
                }
            },
            "if": {
                "properties": {
                    "state": {
                        "enum": [
                            "UNCREATED"
                        ],
                        "type": "string"
                    }
                },
                "required": [
                    "state"
                ]
            },
            "then": {
                "$ref": "#/definitions/UncreatedGame1_1"
            }
        },
        "JoinGameAction1_0": {
            "defaultProperties": [
            ],
            "properties": {
                "gameId": {
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "join_game"
                    ],
                    "type": "string"
                },
                "playerId": {
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.0"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "playerId",
                "version"
            ],
            "type": "object"
        },
        "JoinGameAction1_1": {
            "defaultProperties": [
            ],
            "properties": {
                "createIfNecessary": {
                    "type": "boolean"
                },
                "gameId": {
                    "type": "string"
                },
                "kind": {
                    "enum": [
                        "join_game"
                    ],
                    "type": "string"
                },
                "playerId": {
                    "type": "string"
                },
                "version": {
                    "enum": [
                        "1.1"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "gameId",
                "kind",
                "playerId",
                "version"
            ],
            "type": "object"
        },
        "NumberValue": {
            "defaultProperties": [
            ],
            "properties": {
                "actionId": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            },
            "required": [
                "actionId",
                "value"
            ],
            "type": "object"
        },
        "SavedAction": {
            "defaultProperties": [
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/JoinGameAction1_0"
                },
                "parents": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "required": [
                "action",
                "parents"
            ],
            "type": "object"
        },
        "SavedState": {
            "defaultProperties": [
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/Game1_0"
                }
            },
            "required": [
                "action"
            ],
            "type": "object"
        },
        "Symlink": {
            "defaultProperties": [
            ],
            "properties": {
                "actionId": {
                    "type": "string"
                },
                "value": {
                }
            },
            "required": [
                "actionId",
                "value"
            ],
            "type": "object"
        },
        "TaggedGame1_0": {
            "allOf": [
                {
                    "$ref": "#/definitions/Game1_0"
                },
                {
                    "defaultProperties": [
                    ],
                    "properties": {
                        "actionId": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "actionId"
                    ],
                    "type": "object"
                }
            ]
        },
        "TaggedGame1_1": {
            "anyOf": [
                {
                    "allOf": [
                        {
                            "$ref": "#/definitions/UncreatedGame1_1"
                        },
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "actionId": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "actionId"
                            ],
                            "type": "object"
                        }
                    ]
                },
                {
                    "allOf": [
                        {
                            "$ref": "#/definitions/CreatedGame1_1"
                        },
                        {
                            "defaultProperties": [
                            ],
                            "properties": {
                                "actionId": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "actionId"
                            ],
                            "type": "object"
                        }
                    ]
                }
            ]
        },
        "Timestamp": {
            "defaultProperties": [
            ],
            "properties": {
                "nanoseconds": {
                    "type": "number"
                },
                "seconds": {
                    "type": "number"
                }
            },
            "required": [
                "nanoseconds",
                "seconds"
            ],
            "type": "object"
        },
        "Timestamped": {
            "defaultProperties": [
            ],
            "properties": {
                "timestamp": {
                    "$ref": "#/definitions/Timestamp"
                }
            },
            "required": [
                "timestamp"
            ],
            "type": "object"
        },
        "TimestampedAction": {
            "allOf": [
                {
                    "$ref": "#/definitions/JoinGameAction1_0"
                },
                {
                    "$ref": "#/definitions/Timestamped"
                }
            ]
        },
        "UncreatedGame1_1": {
            "defaultProperties": [
            ],
            "properties": {
                "state": {
                    "enum": [
                        "UNCREATED"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "state"
            ],
            "type": "object"
        }
    }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'Timestamp'): (value: unknown) => Timestamp;
export function validate(typeName: 'Timestamped'): (value: unknown) => Timestamped;
export function validate(typeName: 'NumberValue'): (value: unknown) => NumberValue;
export function validate(typeName: 'Symlink'): (value: unknown) => Symlink;
export function validate(typeName: 'JoinGameAction1_0'): (value: unknown) => JoinGameAction1_0;
export function validate(typeName: 'Action1_0'): (value: unknown) => Action1_0;
export function validate(typeName: 'Game1_0'): (value: unknown) => Game1_0;
export function validate(typeName: 'TaggedGame1_0'): (value: unknown) => TaggedGame1_0;
export function validate(typeName: 'SavedAction'): (value: unknown) => SavedAction;
export function validate(typeName: 'SavedState'): (value: unknown) => SavedState;
export function validate(typeName: 'CreateGameAction1_1'): (value: unknown) => CreateGameAction1_1;
export function validate(typeName: 'JoinGameAction1_1'): (value: unknown) => JoinGameAction1_1;
export function validate(typeName: 'Action1_1'): (value: unknown) => Action1_1;
export function validate(typeName: 'UncreatedGame1_1'): (value: unknown) => UncreatedGame1_1;
export function validate(typeName: 'CreatedGame1_1'): (value: unknown) => CreatedGame1_1;
export function validate(typeName: 'Game1_1'): (value: unknown) => Game1_1;
export function validate(typeName: 'TaggedGame1_1'): (value: unknown) => TaggedGame1_1;
export function validate(typeName: 'AnyAction'): (value: unknown) => AnyAction;
export function validate(typeName: 'TimestampedAction'): (value: unknown) => TimestampedAction;
export function validate(typeName: string): (value: unknown) => any {
    const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
    return (value: unknown): any => {
        if (!validator) {
            throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
        }

        const valid = validator(value);

        if (!valid) {
            throw new Error(
                'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), { dataVar: typeName }),
            );
        }

        return value as any;
    };
}
