/* tslint:disable */
// generated by typescript-json-validator
import Ajv = require('ajv');
import {Strand, Row, BraidAddr, StrandAddr, RowAddr, MountAddr, Mount, Timestamp, Export} from './log';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Strand, Row, BraidAddr, StrandAddr, RowAddr, MountAddr, Mount, Timestamp, Export};
export const Schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BraidAddr": {
      "defaultProperties": [
      ],
      "properties": {
        "braidId": {
          "type": "string"
        }
      },
      "required": [
        "braidId"
      ],
      "type": "object"
    },
    "Export": {
      "additionalProperties": {
      },
      "defaultProperties": [
      ],
      "type": "object"
    },
    "Mount": {
      "defaultProperties": [
      ],
      "properties": {
        "content": {
          "type": "string"
        }
      },
      "required": [
        "content"
      ],
      "type": "object"
    },
    "MountAddr": {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "braidId": {
              "type": "string"
            }
          },
          "required": [
            "braidId"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "strandId": {
              "type": "string"
            }
          },
          "required": [
            "strandId"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "rowIdx": {
              "type": "number"
            }
          },
          "required": [
            "rowIdx"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "mountId": {
              "type": "string"
            }
          },
          "required": [
            "mountId"
          ],
          "type": "object"
        }
      ]
    },
    "Row": {
      "defaultProperties": [
      ],
      "properties": {
        "aliases": {
          "items": {
            "allOf": [
              {
                "defaultProperties": [
                ],
                "properties": {
                  "braidId": {
                    "type": "string"
                  }
                },
                "required": [
                  "braidId"
                ],
                "type": "object"
              },
              {
                "defaultProperties": [
                ],
                "properties": {
                  "strandId": {
                    "type": "string"
                  }
                },
                "required": [
                  "strandId"
                ],
                "type": "object"
              },
              {
                "defaultProperties": [
                ],
                "properties": {
                  "rowIdx": {
                    "type": "number"
                  }
                },
                "required": [
                  "rowIdx"
                ],
                "type": "object"
              }
            ]
          },
          "type": "array"
        },
        "source": {
          "type": "string"
        },
        "timestamp": {
          "defaultProperties": [
          ],
          "properties": {
            "nanoseconds": {
              "type": "number"
            },
            "seconds": {
              "type": "number"
            }
          },
          "required": [
            "nanoseconds",
            "seconds"
          ],
          "type": "object"
        }
      },
      "required": [
        "aliases",
        "source"
      ],
      "type": "object"
    },
    "RowAddr": {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "braidId": {
              "type": "string"
            }
          },
          "required": [
            "braidId"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "strandId": {
              "type": "string"
            }
          },
          "required": [
            "strandId"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "rowIdx": {
              "type": "number"
            }
          },
          "required": [
            "rowIdx"
          ],
          "type": "object"
        }
      ]
    },
    "Strand": {
      "defaultProperties": [
      ],
      "properties": {
        "mountCounts": {
          "additionalProperties": {
            "type": "number"
          },
          "defaultProperties": [
          ],
          "type": "object"
        },
        "sourceCount": {
          "type": "number"
        }
      },
      "required": [
        "mountCounts",
        "sourceCount"
      ],
      "type": "object"
    },
    "StrandAddr": {
      "allOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "braidId": {
              "type": "string"
            }
          },
          "required": [
            "braidId"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "strandId": {
              "type": "string"
            }
          },
          "required": [
            "strandId"
          ],
          "type": "object"
        }
      ]
    },
    "Timestamp": {
      "defaultProperties": [
      ],
      "properties": {
        "nanoseconds": {
          "type": "number"
        },
        "seconds": {
          "type": "number"
        }
      },
      "required": [
        "nanoseconds",
        "seconds"
      ],
      "type": "object"
    }
  }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'Strand'): (value: unknown) => Strand;
export function validate(typeName: 'Row'): (value: unknown) => Row;
export function validate(typeName: 'BraidAddr'): (value: unknown) => BraidAddr;
export function validate(typeName: 'StrandAddr'): (value: unknown) => StrandAddr;
export function validate(typeName: 'RowAddr'): (value: unknown) => RowAddr;
export function validate(typeName: 'MountAddr'): (value: unknown) => MountAddr;
export function validate(typeName: 'Mount'): (value: unknown) => Mount;
export function validate(typeName: 'Timestamp'): (value: unknown) => Timestamp;
export function validate(typeName: 'Export'): (value: unknown) => Export;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
    }
  
    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: typeName}),
      );
    }

    return value as any;
  };
}