/* tslint:disable */
// generated by typescript-json-validator
import Ajv = require('ajv');
import {Action, JoinGame, StartGame, MakeMove, History, Game, UnstartedGame, ActiveGame, FinishedGame, Log, Entry, HistoryProjection, PlayerGame} from './types';
import {inspect} from 'util';
export interface KoaContext {
  readonly request?: unknown; // {body?: unknown}
  readonly params?: unknown;
  readonly query?: unknown;
  throw(status: 400, message: string): unknown;
}
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Action, JoinGame, StartGame, MakeMove, History, Game, UnstartedGame, ActiveGame, FinishedGame, Log, Entry, HistoryProjection, PlayerGame};
export const Schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Action": {
      "else": {
        "else": {
          "else": {
            "properties": {
              "kind": {
                "enum": [
                  "join_game",
                  "start_game",
                  "make_move"
                ],
                "type": "string"
              }
            },
            "required": [
              "kind"
            ]
          },
          "if": {
            "properties": {
              "kind": {
                "enum": [
                  "make_move"
                ],
                "type": "string"
              }
            },
            "required": [
              "kind"
            ]
          },
          "then": {
            "defaultProperties": [
            ],
            "properties": {
              "gameId": {
                "type": "string"
              },
              "kind": {
                "enum": [
                  "make_move"
                ],
                "type": "string"
              },
              "playerId": {
                "type": "string"
              },
              "word": {
                "type": "string"
              }
            },
            "required": [
              "gameId",
              "kind",
              "playerId",
              "word"
            ],
            "type": "object"
          }
        },
        "if": {
          "properties": {
            "kind": {
              "enum": [
                "start_game"
              ],
              "type": "string"
            }
          },
          "required": [
            "kind"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "gameId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "start_game"
              ],
              "type": "string"
            },
            "playerId": {
              "type": "string"
            }
          },
          "required": [
            "gameId",
            "kind",
            "playerId"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "kind": {
            "enum": [
              "join_game"
            ],
            "type": "string"
          }
        },
        "required": [
          "kind"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "gameId": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "join_game"
            ],
            "type": "string"
          },
          "playerId": {
            "type": "string"
          }
        },
        "required": [
          "gameId",
          "kind",
          "playerId"
        ],
        "type": "object"
      }
    },
    "ActiveGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "responses": {
          "items": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "ACTIVE"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "responses",
        "state"
      ],
      "type": "object"
    },
    "Entry": {
      "defaultProperties": [
      ],
      "properties": {
        "body": {
          "type": "string"
        }
      },
      "required": [
        "body"
      ],
      "type": "object"
    },
    "FinishedGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "FINISHED"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "state"
      ],
      "type": "object"
    },
    "Game": {
      "else": {
        "else": {
          "else": {
            "properties": {
              "state": {
                "enum": [
                  "UNSTARTED",
                  "ACTIVE",
                  "FINISHED"
                ],
                "type": "string"
              }
            },
            "required": [
              "state"
            ]
          },
          "if": {
            "properties": {
              "state": {
                "enum": [
                  "FINISHED"
                ],
                "type": "string"
              }
            },
            "required": [
              "state"
            ]
          },
          "then": {
            "defaultProperties": [
            ],
            "properties": {
              "playerIds": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "state": {
                "enum": [
                  "FINISHED"
                ],
                "type": "string"
              }
            },
            "required": [
              "playerIds",
              "state"
            ],
            "type": "object"
          }
        },
        "if": {
          "properties": {
            "state": {
              "enum": [
                "ACTIVE"
              ],
              "type": "string"
            }
          },
          "required": [
            "state"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "playerIds": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "responses": {
              "items": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "type": "array"
            },
            "state": {
              "enum": [
                "ACTIVE"
              ],
              "type": "string"
            }
          },
          "required": [
            "playerIds",
            "responses",
            "state"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "state": {
            "enum": [
              "UNSTARTED"
            ],
            "type": "string"
          }
        },
        "required": [
          "state"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "playerIds": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "state": {
            "enum": [
              "UNSTARTED"
            ],
            "type": "string"
          }
        },
        "required": [
          "playerIds",
          "state"
        ],
        "type": "object"
      }
    },
    "History": {
      "defaultProperties": [
      ],
      "properties": {
        "games": {
          "additionalProperties": {
            "anyOf": [
              {
                "defaultProperties": [
                ],
                "properties": {
                  "playerIds": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "state": {
                    "enum": [
                      "UNSTARTED"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "playerIds",
                  "state"
                ],
                "type": "object"
              },
              {
                "defaultProperties": [
                ],
                "properties": {
                  "playerIds": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "responses": {
                    "items": {
                      "items": {
                        "type": "string"
                      },
                      "type": "array"
                    },
                    "type": "array"
                  },
                  "state": {
                    "enum": [
                      "ACTIVE"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "playerIds",
                  "responses",
                  "state"
                ],
                "type": "object"
              },
              {
                "defaultProperties": [
                ],
                "properties": {
                  "playerIds": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "state": {
                    "enum": [
                      "FINISHED"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "playerIds",
                  "state"
                ],
                "type": "object"
              }
            ]
          },
          "defaultProperties": [
          ],
          "type": "object"
        }
      },
      "required": [
        "games"
      ],
      "type": "object"
    },
    "HistoryProjection": {
      "defaultProperties": [
      ],
      "properties": {
        "playerGames": {
          "additionalProperties": {
            "defaultProperties": [
            ],
            "properties": {
              "players": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "state": {
                "enum": [
                  "ACTIVE",
                  "FINISHED",
                  "UNSTARTED"
                ],
                "type": "string"
              }
            },
            "required": [
              "players",
              "state"
            ],
            "type": "object"
          },
          "defaultProperties": [
          ],
          "type": "object"
        }
      },
      "required": [
        "playerGames"
      ],
      "type": "object"
    },
    "JoinGame": {
      "defaultProperties": [
      ],
      "properties": {
        "gameId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "join_game"
          ],
          "type": "string"
        },
        "playerId": {
          "type": "string"
        }
      },
      "required": [
        "gameId",
        "kind",
        "playerId"
      ],
      "type": "object"
    },
    "Log": {
      "defaultProperties": [
      ],
      "properties": {
        "views": {
          "additionalProperties": {
            "type": "number"
          },
          "defaultProperties": [
          ],
          "type": "object"
        }
      },
      "required": [
        "views"
      ],
      "type": "object"
    },
    "MakeMove": {
      "defaultProperties": [
      ],
      "properties": {
        "gameId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "make_move"
          ],
          "type": "string"
        },
        "playerId": {
          "type": "string"
        },
        "word": {
          "type": "string"
        }
      },
      "required": [
        "gameId",
        "kind",
        "playerId",
        "word"
      ],
      "type": "object"
    },
    "PlayerGame": {
      "defaultProperties": [
      ],
      "properties": {
        "players": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "ACTIVE",
            "FINISHED",
            "UNSTARTED"
          ],
          "type": "string"
        }
      },
      "required": [
        "players",
        "state"
      ],
      "type": "object"
    },
    "StartGame": {
      "defaultProperties": [
      ],
      "properties": {
        "gameId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "start_game"
          ],
          "type": "string"
        },
        "playerId": {
          "type": "string"
        }
      },
      "required": [
        "gameId",
        "kind",
        "playerId"
      ],
      "type": "object"
    },
    "UnstartedGame": {
      "defaultProperties": [
      ],
      "properties": {
        "playerIds": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "UNSTARTED"
          ],
          "type": "string"
        }
      },
      "required": [
        "playerIds",
        "state"
      ],
      "type": "object"
    }
  }
};
ajv.addSchema(Schema, 'Schema')
export function validateKoaRequest(typeName: 'Entry'): (ctx: KoaContext) => {
  params: unknown,
  query: unknown,
  body: Entry['body'],
};
export function validateKoaRequest(typeName: string): (ctx: KoaContext) => {
  params: unknown,
  query: unknown,
  body: unknown,
};
export function validateKoaRequest(typeName: string): (ctx: KoaContext) => {
  params: any,
  query: any,
  body: any,
} {
  const params = ajv.getSchema(`Schema#/definitions/${typeName}/properties/params`);
  const query = ajv.getSchema(`Schema#/definitions/${typeName}/properties/query`);
  const body = ajv.getSchema(`Schema#/definitions/${typeName}/properties/body`);
  const validateProperty = (
    prop: string,
    validator: any,
    ctx: KoaContext,
  ): any => {
    const data = prop === 'body' ? ctx.request && (ctx.request as any).body : (ctx as any)[prop];
    if (validator) {
      const valid = validator(data);
  
      if (!valid) {
        ctx.throw(
          400,
          'Invalid request: ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: prop}) + '\n\n' + inspect({params: ctx.params, query: ctx.query, body: ctx.request && (ctx.request as any).body}),
        );
      }
    }
    return data;
  };
  return (ctx) => {
    return {
      params: validateProperty('params', params, ctx),
      query: validateProperty('query', query, ctx),
      body: validateProperty('body', body, ctx),
    }
  };
}
export function validate(typeName: 'Action'): (value: unknown) => Action;
export function validate(typeName: 'JoinGame'): (value: unknown) => JoinGame;
export function validate(typeName: 'StartGame'): (value: unknown) => StartGame;
export function validate(typeName: 'MakeMove'): (value: unknown) => MakeMove;
export function validate(typeName: 'History'): (value: unknown) => History;
export function validate(typeName: 'Game'): (value: unknown) => Game;
export function validate(typeName: 'UnstartedGame'): (value: unknown) => UnstartedGame;
export function validate(typeName: 'ActiveGame'): (value: unknown) => ActiveGame;
export function validate(typeName: 'FinishedGame'): (value: unknown) => FinishedGame;
export function validate(typeName: 'Log'): (value: unknown) => Log;
export function validate(typeName: 'Entry'): (value: unknown) => Entry;
export function validate(typeName: 'HistoryProjection'): (value: unknown) => HistoryProjection;
export function validate(typeName: 'PlayerGame'): (value: unknown) => PlayerGame;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
    }
  
    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: typeName}),
      );
    }

    return value as any;
  };
}